spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/people
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true